### PR TITLE
v2.5.0-beta.1

### PR DESCRIPTION
**Pull request by 1ec5**
Updated the Xcode project and CocoaPods podspec for v2.5.0-beta.1.

/cc @mapbox/navigation-ios

### CODE REVIEW

**Comment by 1ec5** [comment]
[Tests are failing](https://app.circleci.com/jobs/github/mapbox/mapbox-directions-swift/6453?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link):

```
Test Case 'IntersectionTests.testCoding' started at 2022-05-06 20:35:33.796
/root/project/Tests/MapboxDirectionsTests/IntersectionTests.swift:120: error: IntersectionTests.testCoding : XCTAssertTrue failed - 
Test Case 'IntersectionTests.testCoding' failed (0.002 seconds)
```

Looks like it’s caused by #691 somehow, but tests were passing in that PR. Maybe #669 made the test stricter somehow.

File: Sources/MapboxDirections/TollCollection.swift [hunk 1]
```diff
@@ -39,13 +39,15 @@ public struct TollCollection: Codable, Equatable, ForeignMemberContainer {
     public init(from decoder: Decoder) throws {
         let container = try decoder.container(keyedBy: CodingKeys.self)
         type = try container.decode(CollectionType.self, forKey: .type)
+        name = try container.decodeIfPresent(String.self, forKey: .name)
```
Comment (1ec5) [inline Sources/MapboxDirections/TollCollection.swift:42]: I think #669 caused the coding round-tripping tests to get stricter about properties that fail to round-trip. That’s a good thing!

/cc @Udumft @jill-cardamon

**Review by ShanMa1991 — APPROVED** [review]
